//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 3/12/2012 4:06:35 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace MainContextModel
{

    /// <summary>
    /// There are no comments for MainContextModel.Contact in the schema.
    /// </summary>
    public partial class Contact    {

        #region Properties
    
        /// <summary>
        /// There are no comments for IDCONTACT in the schema.
        /// </summary>
        public virtual long IDCONTACT
        {
            get
            {
                return _IDCONTACT;
            }
            set
            {
                if (_IDCONTACT != value)
                {
                    _IDCONTACT = value;
                }
            }
        }
        private long _IDCONTACT;

    
        /// <summary>
        /// There are no comments for IDBASE in the schema.
        /// </summary>
        public virtual long IDBASE
        {
            get
            {
                return _IDBASE;
            }
            set
            {
                if (_IDBASE != value)
                {
                    _IDBASE = value;
                }
            }
        }
        private long _IDBASE;

    
        /// <summary>
        /// There are no comments for CODECONTACT in the schema.
        /// </summary>
        public virtual string CODECONTACT
        {
            get
            {
                return _CODECONTACT;
            }
            set
            {
                if (_CODECONTACT != value)
                {
                    _CODECONTACT = value;
                }
            }
        }
        private string _CODECONTACT;

    
        /// <summary>
        /// There are no comments for TYPE in the schema.
        /// </summary>
        public virtual long TYPE
        {
            get
            {
                return _TYPE;
            }
            set
            {
                if (_TYPE != value)
                {
                    _TYPE = value;
                }
            }
        }
        private long _TYPE;

    
        /// <summary>
        /// There are no comments for RCS in the schema.
        /// </summary>
        public virtual string RCS
        {
            get
            {
                return _RCS;
            }
            set
            {
                if (_RCS != value)
                {
                    _RCS = value;
                }
            }
        }
        private string _RCS;

    
        /// <summary>
        /// There are no comments for SIRET in the schema.
        /// </summary>
        public virtual string SIRET
        {
            get
            {
                return _SIRET;
            }
            set
            {
                if (_SIRET != value)
                {
                    _SIRET = value;
                }
            }
        }
        private string _SIRET;

    
        /// <summary>
        /// There are no comments for TVA in the schema.
        /// </summary>
        public virtual string TVA
        {
            get
            {
                return _TVA;
            }
            set
            {
                if (_TVA != value)
                {
                    _TVA = value;
                }
            }
        }
        private string _TVA;

    
        /// <summary>
        /// There are no comments for IDEXTERNE in the schema.
        /// </summary>
        public virtual string IDEXTERNE
        {
            get
            {
                return _IDEXTERNE;
            }
            set
            {
                if (_IDEXTERNE != value)
                {
                    _IDEXTERNE = value;
                }
            }
        }
        private string _IDEXTERNE;

    
        /// <summary>
        /// There are no comments for RNBJR in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> RNBJR
        {
            get
            {
                return _RNBJR;
            }
            set
            {
                if (_RNBJR != value)
                {
                    _RNBJR = value;
                }
            }
        }
        private global::System.Nullable<int> _RNBJR;

    
        /// <summary>
        /// There are no comments for RLE in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> RLE
        {
            get
            {
                return _RLE;
            }
            set
            {
                if (_RLE != value)
                {
                    _RLE = value;
                }
            }
        }
        private global::System.Nullable<int> _RLE;

    
        /// <summary>
        /// There are no comments for RDOMIC in the schema.
        /// </summary>
        public virtual string RDOMIC
        {
            get
            {
                return _RDOMIC;
            }
            set
            {
                if (_RDOMIC != value)
                {
                    _RDOMIC = value;
                }
            }
        }
        private string _RDOMIC;

    
        /// <summary>
        /// There are no comments for RDOMIC2 in the schema.
        /// </summary>
        public virtual string RDOMIC2
        {
            get
            {
                return _RDOMIC2;
            }
            set
            {
                if (_RDOMIC2 != value)
                {
                    _RDOMIC2 = value;
                }
            }
        }
        private string _RDOMIC2;

    
        /// <summary>
        /// There are no comments for LOGO in the schema.
        /// </summary>
        public virtual string LOGO
        {
            get
            {
                return _LOGO;
            }
            set
            {
                if (_LOGO != value)
                {
                    _LOGO = value;
                }
            }
        }
        private string _LOGO;

    
        /// <summary>
        /// There are no comments for COMM in the schema.
        /// </summary>
        public virtual string COMM
        {
            get
            {
                return _COMM;
            }
            set
            {
                if (_COMM != value)
                {
                    _COMM = value;
                }
            }
        }
        private string _COMM;

    
        /// <summary>
        /// There are no comments for CQUI in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> CQUI
        {
            get
            {
                return _CQUI;
            }
            set
            {
                if (_CQUI != value)
                {
                    _CQUI = value;
                }
            }
        }
        private global::System.Nullable<long> _CQUI;

    
        /// <summary>
        /// There are no comments for CDATE in the schema.
        /// </summary>
        public virtual global::System.Nullable<System.DateTime> CDATE
        {
            get
            {
                return _CDATE;
            }
            set
            {
                if (_CDATE != value)
                {
                    _CDATE = value;
                }
            }
        }
        private global::System.Nullable<System.DateTime> _CDATE;

    
        /// <summary>
        /// There are no comments for CHEURE in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> CHEURE
        {
            get
            {
                return _CHEURE;
            }
            set
            {
                if (_CHEURE != value)
                {
                    _CHEURE = value;
                }
            }
        }
        private global::System.Nullable<int> _CHEURE;

    
        /// <summary>
        /// There are no comments for CSITE in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> CSITE
        {
            get
            {
                return _CSITE;
            }
            set
            {
                if (_CSITE != value)
                {
                    _CSITE = value;
                }
            }
        }
        private global::System.Nullable<long> _CSITE;

    
        /// <summary>
        /// There are no comments for MQUI in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> MQUI
        {
            get
            {
                return _MQUI;
            }
            set
            {
                if (_MQUI != value)
                {
                    _MQUI = value;
                }
            }
        }
        private global::System.Nullable<long> _MQUI;

    
        /// <summary>
        /// There are no comments for MDATE in the schema.
        /// </summary>
        public virtual global::System.Nullable<System.DateTime> MDATE
        {
            get
            {
                return _MDATE;
            }
            set
            {
                if (_MDATE != value)
                {
                    _MDATE = value;
                }
            }
        }
        private global::System.Nullable<System.DateTime> _MDATE;

    
        /// <summary>
        /// There are no comments for MHEURE in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> MHEURE
        {
            get
            {
                return _MHEURE;
            }
            set
            {
                if (_MHEURE != value)
                {
                    _MHEURE = value;
                }
            }
        }
        private global::System.Nullable<int> _MHEURE;

    
        /// <summary>
        /// There are no comments for MSITE in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> MSITE
        {
            get
            {
                return _MSITE;
            }
            set
            {
                if (_MSITE != value)
                {
                    _MSITE = value;
                }
            }
        }
        private global::System.Nullable<long> _MSITE;

    
        /// <summary>
        /// There are no comments for ADRESSEPRINCIP in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> ADRESSEPRINCIP
        {
            get
            {
                return _ADRESSEPRINCIP;
            }
            set
            {
                if (_ADRESSEPRINCIP != value)
                {
                    _ADRESSEPRINCIP = value;
                }
            }
        }
        private global::System.Nullable<long> _ADRESSEPRINCIP;

    
        /// <summary>
        /// There are no comments for IDMODEREGLEMENT in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> IDMODEREGLEMENT
        {
            get
            {
                return _IDMODEREGLEMENT;
            }
            set
            {
                if (_IDMODEREGLEMENT != value)
                {
                    _IDMODEREGLEMENT = value;
                }
            }
        }
        private global::System.Nullable<long> _IDMODEREGLEMENT;

    
        /// <summary>
        /// There are no comments for ADRESSEMAILING in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> ADRESSEMAILING
        {
            get
            {
                return _ADRESSEMAILING;
            }
            set
            {
                if (_ADRESSEMAILING != value)
                {
                    _ADRESSEMAILING = value;
                }
            }
        }
        private global::System.Nullable<long> _ADRESSEMAILING;

    
        /// <summary>
        /// There are no comments for CHANGEBASE in the schema.
        /// </summary>
        public virtual global::System.Nullable<System.DateTime> CHANGEBASE
        {
            get
            {
                return _CHANGEBASE;
            }
            set
            {
                if (_CHANGEBASE != value)
                {
                    _CHANGEBASE = value;
                }
            }
        }
        private global::System.Nullable<System.DateTime> _CHANGEBASE;

    
        /// <summary>
        /// There are no comments for BASEPRECED in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> BASEPRECED
        {
            get
            {
                return _BASEPRECED;
            }
            set
            {
                if (_BASEPRECED != value)
                {
                    _BASEPRECED = value;
                }
            }
        }
        private global::System.Nullable<long> _BASEPRECED;

    
        /// <summary>
        /// There are no comments for IDCONDREGLEMENT in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> IDCONDREGLEMENT
        {
            get
            {
                return _IDCONDREGLEMENT;
            }
            set
            {
                if (_IDCONDREGLEMENT != value)
                {
                    _IDCONDREGLEMENT = value;
                }
            }
        }
        private global::System.Nullable<long> _IDCONDREGLEMENT;

    
        /// <summary>
        /// There are no comments for IDDEVISE in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> IDDEVISE
        {
            get
            {
                return _IDDEVISE;
            }
            set
            {
                if (_IDDEVISE != value)
                {
                    _IDDEVISE = value;
                }
            }
        }
        private global::System.Nullable<long> _IDDEVISE;

    
        /// <summary>
        /// There are no comments for IBAN in the schema.
        /// </summary>
        public virtual string IBAN
        {
            get
            {
                return _IBAN;
            }
            set
            {
                if (_IBAN != value)
                {
                    _IBAN = value;
                }
            }
        }
        private string _IBAN;

    
        /// <summary>
        /// There are no comments for IDAPE in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> IDAPE
        {
            get
            {
                return _IDAPE;
            }
            set
            {
                if (_IDAPE != value)
                {
                    _IDAPE = value;
                }
            }
        }
        private global::System.Nullable<long> _IDAPE;

    
        /// <summary>
        /// There are no comments for CONDRGTPART in the schema.
        /// </summary>
        public virtual string CONDRGTPART
        {
            get
            {
                return _CONDRGTPART;
            }
            set
            {
                if (_CONDRGTPART != value)
                {
                    _CONDRGTPART = value;
                }
            }
        }
        private string _CONDRGTPART;

    
        /// <summary>
        /// There are no comments for IDCATTARIF in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> IDCATTARIF
        {
            get
            {
                return _IDCATTARIF;
            }
            set
            {
                if (_IDCATTARIF != value)
                {
                    _IDCATTARIF = value;
                }
            }
        }
        private global::System.Nullable<long> _IDCATTARIF;

    
        /// <summary>
        /// There are no comments for CONDCIALREMISE in the schema.
        /// </summary>
        public virtual global::System.Nullable<decimal> CONDCIALREMISE
        {
            get
            {
                return _CONDCIALREMISE;
            }
            set
            {
                if (_CONDCIALREMISE != value)
                {
                    _CONDCIALREMISE = value;
                }
            }
        }
        private global::System.Nullable<decimal> _CONDCIALREMISE;

    
        /// <summary>
        /// There are no comments for CONDCIALENCOURS in the schema.
        /// </summary>
        public virtual global::System.Nullable<decimal> CONDCIALENCOURS
        {
            get
            {
                return _CONDCIALENCOURS;
            }
            set
            {
                if (_CONDCIALENCOURS != value)
                {
                    _CONDCIALENCOURS = value;
                }
            }
        }
        private global::System.Nullable<decimal> _CONDCIALENCOURS;

    
        /// <summary>
        /// There are no comments for CONDCIALACCORD in the schema.
        /// </summary>
        public virtual global::System.Nullable<System.DateTime> CONDCIALACCORD
        {
            get
            {
                return _CONDCIALACCORD;
            }
            set
            {
                if (_CONDCIALACCORD != value)
                {
                    _CONDCIALACCORD = value;
                }
            }
        }
        private global::System.Nullable<System.DateTime> _CONDCIALACCORD;

    
        /// <summary>
        /// There are no comments for CONDCIALACCORDQUI in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> CONDCIALACCORDQUI
        {
            get
            {
                return _CONDCIALACCORDQUI;
            }
            set
            {
                if (_CONDCIALACCORDQUI != value)
                {
                    _CONDCIALACCORDQUI = value;
                }
            }
        }
        private global::System.Nullable<long> _CONDCIALACCORDQUI;

    
        /// <summary>
        /// There are no comments for IDCOMMERCIAL in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> IDCOMMERCIAL
        {
            get
            {
                return _IDCOMMERCIAL;
            }
            set
            {
                if (_IDCOMMERCIAL != value)
                {
                    _IDCOMMERCIAL = value;
                }
            }
        }
        private global::System.Nullable<long> _IDCOMMERCIAL;

    
        /// <summary>
        /// There are no comments for IDDOSSIER in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> IDDOSSIER
        {
            get
            {
                return _IDDOSSIER;
            }
            set
            {
                if (_IDDOSSIER != value)
                {
                    _IDDOSSIER = value;
                }
            }
        }
        private global::System.Nullable<long> _IDDOSSIER;

    
        /// <summary>
        /// There are no comments for SOMMEIL in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> SOMMEIL
        {
            get
            {
                return _SOMMEIL;
            }
            set
            {
                if (_SOMMEIL != value)
                {
                    _SOMMEIL = value;
                }
            }
        }
        private global::System.Nullable<int> _SOMMEIL;

    
        /// <summary>
        /// There are no comments for LOGIN in the schema.
        /// </summary>
        public virtual string LOGIN
        {
            get
            {
                return _LOGIN;
            }
            set
            {
                if (_LOGIN != value)
                {
                    _LOGIN = value;
                }
            }
        }
        private string _LOGIN;

    
        /// <summary>
        /// There are no comments for PASSWORD in the schema.
        /// </summary>
        public virtual string PASSWORD
        {
            get
            {
                return _PASSWORD;
            }
            set
            {
                if (_PASSWORD != value)
                {
                    _PASSWORD = value;
                }
            }
        }
        private string _PASSWORD;

    
        /// <summary>
        /// There are no comments for IDMOTIFSOMMEIL in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> IDMOTIFSOMMEIL
        {
            get
            {
                return _IDMOTIFSOMMEIL;
            }
            set
            {
                if (_IDMOTIFSOMMEIL != value)
                {
                    _IDMOTIFSOMMEIL = value;
                }
            }
        }
        private global::System.Nullable<long> _IDMOTIFSOMMEIL;

    
        /// <summary>
        /// There are no comments for DATESOMMEIL in the schema.
        /// </summary>
        public virtual global::System.Nullable<System.DateTime> DATESOMMEIL
        {
            get
            {
                return _DATESOMMEIL;
            }
            set
            {
                if (_DATESOMMEIL != value)
                {
                    _DATESOMMEIL = value;
                }
            }
        }
        private global::System.Nullable<System.DateTime> _DATESOMMEIL;

    
        /// <summary>
        /// There are no comments for IDQUISOMMEIL in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> IDQUISOMMEIL
        {
            get
            {
                return _IDQUISOMMEIL;
            }
            set
            {
                if (_IDQUISOMMEIL != value)
                {
                    _IDQUISOMMEIL = value;
                }
            }
        }
        private global::System.Nullable<long> _IDQUISOMMEIL;

    
        /// <summary>
        /// There are no comments for IDSITE in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> IDSITE
        {
            get
            {
                return _IDSITE;
            }
            set
            {
                if (_IDSITE != value)
                {
                    _IDSITE = value;
                }
            }
        }
        private global::System.Nullable<long> _IDSITE;

    
        /// <summary>
        /// There are no comments for IDPROFIL in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> IDPROFIL
        {
            get
            {
                return _IDPROFIL;
            }
            set
            {
                if (_IDPROFIL != value)
                {
                    _IDPROFIL = value;
                }
            }
        }
        private global::System.Nullable<long> _IDPROFIL;

    
        /// <summary>
        /// There are no comments for ORGASRVC in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> ORGASRVC
        {
            get
            {
                return _ORGASRVC;
            }
            set
            {
                if (_ORGASRVC != value)
                {
                    _ORGASRVC = value;
                }
            }
        }
        private global::System.Nullable<int> _ORGASRVC;

    
        /// <summary>
        /// There are no comments for IDORGASRVC in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> IDORGASRVC
        {
            get
            {
                return _IDORGASRVC;
            }
            set
            {
                if (_IDORGASRVC != value)
                {
                    _IDORGASRVC = value;
                }
            }
        }
        private global::System.Nullable<long> _IDORGASRVC;

    
        /// <summary>
        /// There are no comments for IDSTATUT in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> IDSTATUT
        {
            get
            {
                return _IDSTATUT;
            }
            set
            {
                if (_IDSTATUT != value)
                {
                    _IDSTATUT = value;
                }
            }
        }
        private global::System.Nullable<long> _IDSTATUT;

    
        /// <summary>
        /// There are no comments for IDSOUSSTATUT in the schema.
        /// </summary>
        public virtual global::System.Nullable<long> IDSOUSSTATUT
        {
            get
            {
                return _IDSOUSSTATUT;
            }
            set
            {
                if (_IDSOUSSTATUT != value)
                {
                    _IDSOUSSTATUT = value;
                }
            }
        }
        private global::System.Nullable<long> _IDSOUSSTATUT;

    
        /// <summary>
        /// There are no comments for ANNUAIRE in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> ANNUAIRE
        {
            get
            {
                return _ANNUAIRE;
            }
            set
            {
                if (_ANNUAIRE != value)
                {
                    _ANNUAIRE = value;
                }
            }
        }
        private global::System.Nullable<int> _ANNUAIRE;

    
        /// <summary>
        /// There are no comments for OA_ANNUAIRE in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> OA_ANNUAIRE
        {
            get
            {
                return _OA_ANNUAIRE;
            }
            set
            {
                if (_OA_ANNUAIRE != value)
                {
                    _OA_ANNUAIRE = value;
                }
            }
        }
        private global::System.Nullable<int> _OA_ANNUAIRE;


        #endregion
    }

}
